### PR TITLE
Add support to provide private key as string in addition to file path

### PR DESCRIPTION
**Pull request by chris1312**

### CODE REVIEW

**Comment by tvdijen** [comment]
Excellent @chris1312, I've tagged a new release for you!

**Comment by chris1312** [comment]
Awesome, thanks!

**Comment by tvdijen** [comment]
@chris1312 : Just so you know, I had to release v3.4.1 already because v3.4.0 was accidentally based on `master` instead of the `release-3.x` branch

**Comment by chris1312** [comment]
Thanks for update. Was that my fault?

**Comment by tvdijen** [comment]
No absolutely not, it was me during the process of releasing a new version

**Pull request merged**
