### PR TITLE
Implement namespaces and PSR2 compliance

### PR DESCRIPTION
**Pull request by DRvanR**
Based on the awesome work of @cb8 in #53

- has been rebased on `master`, conflicts have been resolved, new code has been adapted
- testsuite has been fixed
- README has been updated to include version information

### CODE REVIEW

**Comment by DRvanR** [comment]
Closes #53 

Any feedback on the last 3 commits @thijskh, @relaxnow or @jaimeperez? If not I'll merge this tomorrow morning (CET), create the release 2.x branch and tag release 2.0.0

**Comment by thijskh** [comment]
No objections from me!

**Comment by jaimeperez** [comment]
Didn't have time to look at it carefully, but it should be ok, so :+1: from me too.

**Comment by relaxnow** [comment]
:+1:

**Pull request merged**
