### PR TITLE
Bump xmlseclibs version

### PR DESCRIPTION
**Pull request by chris1312**
#97

### CODE REVIEW

**Comment by thijskh** [comment]
If you also bump the `composer.lock` then Travis can show us whether the testsuite still passes (spoiler: it does).

**Comment by chris1312** [comment]
Sorry, I did not catch.. 

This project does not contain `composer.lock`. Do you say that you want me to commit `composer.lock` into the project? I see in Travis build (e.g. for PHP7) that the 3.0.0 version of `xmlseclibs` was installed.

**Comment by thijskh** [comment]
Indeed, my mistake. The tests pass, that's a good start!

**Comment by chris1312** [comment]
Is there anything more you expect from this pull request?

**Comment by thijskh** [comment]
Not per se, just need to find some time to do some further testing, then merge.

**Comment by jaimeperez** [comment]
Hi @chris1312!

I would also like to see how the discussion in robrichards/xmlseclibs#123 ends up before we trust the 3.0.0 to be stable and final. I'm afraid of bumping the version here to see days afterwards that it was removed to merge that PR instead.

That said, I'm really looking forward to this myself too...

**Comment by chris1312** [comment]
OK, sure!

**Comment by thijskh** [comment]
@jaimeperez Those two pr's are functionally the same, right? So would it matter much to change later?

**Comment by jaimeperez** [comment]
Nah, I don't think there'll be changes to the code (not significantly anyway). I'm just afraid of some kind of mess if Rob tries to fix it so that proper credit is given to the code by merging the existing PR, but he doesn't seem to be responsive at all, and if something breaks, we can always fix it.

So given that we are in master here, 👍 from me too.

**Comment by thijskh** [comment]
Thanks for your contribution!

**Pull request merged**
