### PR TITLE
Add support to provide private key as string in addition to file path

### PR DESCRIPTION
**Pull request by chris1312**
#171

### CODE REVIEW

**Comment by chris1312** [comment]
It seems some checks are failing that are not related to my changes.

**Comment by tvdijen** [comment]
Yes, it appears Psalm is able to detect more issues than it did before.. You can ignore this

**Comment by chris1312** [comment]
@tvdijen is there anything I should fix/improve for this PR?

**Comment by tvdijen** [comment]
Hi @chris1312 !
All is fine, I just approved it.. Waiting for a second pair of eyes before merging

**Comment by chris1312** [comment]
Awesome, thx!

**Comment by chris1312** [comment]
Where can I find info about release cycle? Is it expected to be released soon? :)

**Comment by chris1312** [comment]
@tvdijen any ideas when this feature will be released?

**Comment by tvdijen** [comment]
Hi @chris1312, sorry I missed your earlier message..
This was merged to master and has PHP7-specific code (return types, scalar type hints), so it would have to wait for 4.0 to be released (which I don't expect any time soon, or even the next year).

If you really have an urgent need for this, a new PR for the 3.x branch would be the fastest.. I can tag a 3.4 release for you then.

**Pull request merged**
